### ISSUE TITLE
Add topic tags

### ISSUE THREAD

**Issue by Beliavsky** [thechibo/estim#1]
I suggest adding topics such as `r`, `r-package`, `probability-distribution`, `statistics`, `maximum-likelihood`, `estimation` in the About section, as explained at https://docs.github.com/en/enterprise-cloud@latest/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by thechibo** [comment]
Dear Beliavsky,
Thank you very much for the suggestion. I added the topics in the About section!
